services:
    bank-drf:
        build: .
        container_name: bank-drf
        env_file:
            - .env
        ports:
            - "8000:8000"
        command: "python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./bank-drf:/app/bank-drf
        depends_on:
            - pgdb

    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
